In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df_doctoralia = pd.read_csv('202210_doctoralia_br.csv')
df_doctoralia.head()

,doctor_id,title,name,city1,city2,region,specialization,reviews,newest_review_date,telemedicine,price,url,fetch_time
0,7749,Dr.,Octavio Grecco,São Paulo,sao-paulo,sao-paulo-sp,alergista,5.0,2022-10-13T16:50:21-03:00,0,800,http://www.doctoralia.com.br/octavio-grecco,2022-10-28 20:55:01
1,424668,Dra.,Marcia Toraiwa Iwashita,São Paulo,sao-paulo,sao-paulo-sp,alergista,41.0,2022-10-25T13:28:19-03:00,1,600,http://www.doctoralia.com.br/marcia-toraiwa-iw...,2022-10-28 20:55:02
2,758125,Dra.,Pamela Fernanda Alves Barbosa,São Paulo,sao-paulo,sao-paulo-sp,alergista,19.0,2022-10-19T21:24:28-03:00,0,490,http://www.doctoralia.com.br/pamela-fernanda-a...,2022-10-28 20:55:05
3,544831,Dra.,Marilene Ricci Ganem,São Paulo,sao-paulo,sao-paulo-sp,alergista,114.0,2022-10-18T12:21:51-03:00,1,300,http://www.doctoralia.com.br/marilene-ricci-ganem,2022-10-28 20:55:06
4,719643,Dra.,Gabriela De Oliveira Ferreira,Campina Grande,campina-grande,paraiba-pb,alergista,164.0,2022-10-28T12:03:08-03:00,1,350,http://www.doctoralia.com.br/gabriela-de-olive...,2022-10-28 20:55:08

1. O preço da consulta é caro por causa da especialização.
2. A consulta é cara por causa da região (cidade ou estado).
3. A quantidade de reviews influencia o preço da consulta.
4. Atender por telemedicina influencia o preço da consulta.
5. Gênero X Preço
6. Região/Cidade x preço

In [4]:
arr_quanti = ['reviews', 'price']
arr_quali = ['title', 'city1', 'region', 'specialization', 'telemedicine']

df_doctoralia_quant = df_doctoralia[arr_quanti]
df_doctoralia_quali = df_doctoralia[arr_quali]

In [5]:
df_doctoralia_quant

        reviews price
0           5.0   800
1          41.0   600
2          19.0   490
3         114.0   300
4         164.0   350
...         ...   ...
165057      NaN   NaN
165058      NaN   NaN
165059      NaN   200
165060      NaN   200
165061      NaN   NaN

[165062 rows x 2 columns]

In [6]:
df_doctoralia_quali

       title             city1           region specialization  telemedicine
0        Dr.         São Paulo     sao-paulo-sp      alergista             0
1       Dra.         São Paulo     sao-paulo-sp      alergista             1
2       Dra.         São Paulo     sao-paulo-sp      alergista             0
3       Dra.         São Paulo     sao-paulo-sp      alergista             1
4       Dra.    Campina Grande       paraiba-pb      alergista             1
...      ...               ...              ...            ...           ...
165057   NaN          Rolândia        parana-pr  nutricionista             0
165058   NaN  Feira de Santana         bahia-ba  nutricionista             0
165059   NaN    Belo Horizonte  minas-gerais-mg  nutricionista             0
165060   NaN     Belém do Pará          para-pa  nutricionista             0
165061   NaN    Campina Grande       paraiba-pb  nutricionista             0

[165062 rows x 5 columns]